version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bookings
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d bookings"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/bookings?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy