apiVersion: v1
kind: Service
metadata:
  name: bookings-backend-api-service
spec:
  selector:
    app: bookings-backend-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer